/**
 * src/data/curriculum/units.generated.ts
 *
 * AUTO-GENERATED by the curriculum scripts — DO NOT EDIT BY HAND.
 * Add a unit: create `units/mNN.json`, then run `npm run curriculum:barrel`.
 */
import m01 from './units/m01.json';
import m02 from './units/m02.json';
import m03 from './units/m03.json';
import m04 from './units/m04.json';
import m05 from './units/m05.json';
import m06 from './units/m06.json';
import m07 from './units/m07.json';
import m08 from './units/m08.json';
import m09 from './units/m09.json';
import m10 from './units/m10.json';
import m11 from './units/m11.json';
import m12 from './units/m12.json';
import m13 from './units/m13.json';
import m14 from './units/m14.json';
import m15 from './units/m15.json';
import m16 from './units/m16.json';

import type { CurriculumUnitFile } from './schema';

export const UNIT_FILES: readonly CurriculumUnitFile[] = [
  m01, m02, m03, m04, m05, m06, m07, m08, m09, m10, m11, m12, m13, m14, m15, m16,
] as unknown as readonly CurriculumUnitFile[];
