/**
 * useSpeech — the single entry point for EVERY German utterance in the app.
 *
 * WHY ONE MODULE
 * --------------
 * `AUDIO_BY_LEMMA` (generated by `scripts/bundle-offline-seed.cjs` from the
 * Goethe-Institut A1 deck, CC BY-SA 4.0) holds one bundled MP3 per German
 * lemma under `/audio/anki/`. Previously only `speakWord()` consulted it, so
 * ~30 other surfaces — including the whole A1 checkpoint engine — synthesized
 * speech instead of using the natural recordings. Everything now goes through
 * `speakText()`, which prefers a bundled clip and falls back to `speechSynthesis`.
 *
 * TTS SAFETY (.clinerules C2.6) IS ENFORCED BY THE DATA, NOT BY REVIEW
 * ---------------------------------------------------------------------
 * `AUDIO_BY_LEMMA` is keyed by GERMAN LEMMAS ONLY. A prompt that is English,
 * Nepali, or a multi-word German phrase can never match a key, so
 * `speakText('What does this mean?')` is guaranteed to synthesize rather than
 * play a recording. Routing pre-lock prompt audio through this function
 * therefore cannot leak an answer: the substitution only fires when the spoken
 * string IS a German word, and in every quiz surface the spoken string is
 * either the question (safe) or post-lock (allowed).
 *
 * SPEED
 * -----
 * The Settings control stores `slow | normal | fast` = 0.6 / 0.85 / 1.05 and
 * applies it to synthesized speech. The bundled clips are 22 050 Hz MONO
 * VBR MP3s (measured from the frame headers); at 0.6x a pitch-preserving
 * time-stretcher is audibly smeared, which is the one place a pronunciation app
 * can least afford it. Recordings are therefore CLAMPED to a gentler range while
 * synthesized speech keeps the full spread.
 */

import { useCallback, useEffect, useState } from 'react';
import { getItem, setItem } from '../utils/safeStorage';
import { AUDIO_BY_LEMMA } from '../data/audioManifest';
import { isAudioEnabled } from '../utils/audioEnabled';

export type SpeechSpeed = 'slow' | 'normal' | 'fast';

const SPEED_KEY = 'meroDeutschSpeechSpeed';
const SPEED_RATES: Record<SpeechSpeed, number> = {
  slow: 0.6,
  normal: 0.85,
  fast: 1.05,
};

/**
 * Range a bundled recording may be time-scaled over. See the file header: the
 * clips are 22 kHz mono, and below ~0.8x the time-stretcher smears the
 * fricatives a German learner is being taught to hear.
 */
const RECORDING_RATE_MIN = 0.8;
const RECORDING_RATE_MAX = 1.1;

function loadSpeed(): SpeechSpeed {
  const stored = getItem(SPEED_KEY);
  return stored === 'slow' || stored === 'normal' || stored === 'fast' ? stored : 'normal';
}

function clampRecordingRate(rate: number): number {
  return Math.min(RECORDING_RATE_MAX, Math.max(RECORDING_RATE_MIN, rate));
}

/** The speed the Settings control currently implies for synthesized speech. */
function currentRate(): number {
  return SPEED_RATES[loadSpeed()];
}

/**
 * Ask the browser not to shift pitch when a recording is slowed.
 *
 * `preservesPitch` is the current name; Safari shipped the same behaviour under
 * vendor prefixes for years. Where none is supported the clip simply plays at
 * the raw rate, which is exactly the pre-existing behaviour — so the
 * feature-detect degrades rather than regresses.
 */
function applyPitchPreservation(audio: HTMLAudioElement): void {
  // Cast rather than `in`-narrow: TypeScript knows `preservesPitch` exists on
  // the current DOM lib, so every `in` branch after it narrows to `never`.
  const el = audio as unknown as Record<string, unknown>;
  for (const prop of ['preservesPitch', 'mozPreservesPitch', 'webkitPreservesPitch']) {
    if (prop in el) {
      el[prop] = true;
      return;
    }
  }
}

/** Prefer natural-sounding German voices over robotic defaults. */
function getGermanVoice(): SpeechSynthesisVoice | undefined {
  if (typeof window === 'undefined' || !window.speechSynthesis) return undefined;
  const voices = window.speechSynthesis.getVoices();
  const de = voices.filter((v) => v.lang.toLowerCase().startsWith('de'));
  if (de.length === 0) return undefined;
  const natural = de.find((v) => /natural/i.test(v.name));
  if (natural) return natural;
  const google = de.find((v) => /google/i.test(v.name));
  if (google) return google;
  const female = de.find((v) => /(female|katja|anna|hedda|zira|hazel|susan)/i.test(v.name));
  if (female) return female;
  return de[0];
}

/**
 * Synthesized speech. Honors the global header mute toggle — `audioEnabled.ts`
 * owns that flag; without the guard the single mute button would silence only
 * some sounds.
 */
function synthesize(text: string, rate: number) {
  if (typeof window === 'undefined' || !window.speechSynthesis) return;
  window.speechSynthesis.cancel();
  const u = new SpeechSynthesisUtterance(text);
  u.lang = 'de-DE';
  u.rate = rate;
  const voice = getGermanVoice();
  if (voice) u.voice = voice;
  window.speechSynthesis.speak(u);
}

/** Look up a bundled clip for a German word (case-insensitive lemma match). */
function localAudioFor(text: string): string | null {
  if (!text) return null;
  const key = text.trim().toLowerCase();
  return Object.prototype.hasOwnProperty.call(AUDIO_BY_LEMMA, key) ? AUDIO_BY_LEMMA[key] : null;
}

/**
 * Play a bundled MP3, rate-clamped; on any playback failure fall back to
 * synthesis. Always stops in-flight speech first, so a recording never lands on
 * top of a still-speaking utterance.
 */
function playFile(url: string, fallbackText: string) {
  if (!isAudioEnabled()) return;
  if (typeof window !== 'undefined' && window.speechSynthesis) {
    window.speechSynthesis.cancel();
  }
  const audio = new Audio(url);
  audio.playbackRate = clampRecordingRate(currentRate());
  applyPitchPreservation(audio);
  audio.onerror = () => synthesize(fallbackText, currentRate());

  // `play()` returns a promise in every modern browser, but it is specified to
  // return `undefined` in some older ones, and a test environment without a real
  // media stack does the same. Calling `.catch` on that throws a TypeError from
  // inside a click handler, which surfaces as a blank screen rather than a missing
  // sound. The `onerror` handler above already covers a genuine load failure, so
  // this only has to not explode.
  const played = audio.play() as Promise<void> | undefined;
  if (played && typeof played.catch === 'function') {
    played.catch(() => synthesize(fallbackText, currentRate()));
  }
}

/**
 * Speak German text, preferring a bundled recording.
 *
 * THE ONE FUNCTION EVERY AUDIO SURFACE SHOULD CALL. Because the manifest is
 * keyed by German lemmas only, non-German or multi-word input transparently
 * falls through to synthesis — see the TTS-safety note in the file header.
 */
export function speakText(text: string, rateOverride?: number) {
  if (!isAudioEnabled()) return;
  const bundled = localAudioFor(text);
  if (bundled) {
    playFile(bundled, text);
    return;
  }
  synthesize(text, rateOverride ?? currentRate());
}

export function speakWord(text: string) {
  speakText(text);
}

export function speakLetter(text: string) {
  speakText(text, 0.75);
}

/**
 * Play an arbitrary audio URL (a bundled clip, or a DB/lesson-hosted one),
 * honoring the global mute toggle and the same clamped speed as `speakText`.
 *
 * `fallbackText` is OPTIONAL and deliberately absent at TTS-safe call sites:
 * speaking the target word as a fallback would reveal the answer before the
 * question locks (.clinerules C2.6).
 */
export function playAudioUrl(url: string, fallbackText?: string) {
  if (!isAudioEnabled()) return;
  if (typeof window === 'undefined') return;
  const audio = new Audio(url);
  audio.playbackRate = clampRecordingRate(currentRate());
  applyPitchPreservation(audio);
  if (fallbackText) audio.onerror = () => synthesize(fallbackText, currentRate());
  audio.play().catch(() => {
    if (fallbackText) synthesize(fallbackText, currentRate());
  });
}

/**
 * Global speech-speed control. Persists to localStorage and lets all modules
 * (Alphabet, Numbers, Glossary, Dictation) share one system.
 */
export function useSpeechSpeed() {
  const [speed, setSpeed] = useState<SpeechSpeed>(loadSpeed);

  useEffect(() => {
    setItem(SPEED_KEY, speed);
    // Re-cancel any in-flight utterance so the new rate applies immediately.
    if (typeof window !== 'undefined' && window.speechSynthesis) {
      window.speechSynthesis.cancel();
    }
  }, [speed]);

  const setNextSpeed = useCallback(() => {
    setSpeed((prev) => (prev === 'slow' ? 'normal' : prev === 'normal' ? 'fast' : 'slow'));
  }, []);

  return {
    speed,
    rates: SPEED_RATES,
    setSpeed,
    setNextSpeed,
  };
}

export { SPEED_RATES };
