export const theme = {
  brand: {
    primary: '#2563eb',
    meroRed: '#dc2626',
    accentGold: '#f59e0b',
    meroText: 'Mero',
    deutschText: 'Deutsch',
    tagline: 'Learn German from zero — with Nepali support',
  },
  page: {
    container: 'p-4',
    heading: 'text-xl font-bold',
    description: 'mb-4 text-sm text-slate-500 dark:text-slate-400',
  },
  layout: {
    app: 'min-h-screen bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100',
    header: 'bg-blue-600 text-white shadow-md backdrop-blur-sm sticky top-0 z-50',
    headerInner: 'max-w-6xl mx-auto px-3 py-2.5 flex flex-col sm:flex-row justify-between items-center gap-2',
    brand: 'text-lg font-bold flex items-center gap-1',
    nav: 'flex flex-wrap justify-center gap-1.5',
    navLinkActive: 'px-3 py-1.5 rounded-lg text-sm font-semibold bg-white text-blue-600 shadow',
    navLink: 'px-3 py-1.5 rounded-lg text-sm font-semibold bg-blue-700 text-white border border-blue-500 hover:bg-blue-800',
    toggleButton: 'px-2.5 py-1.5 rounded-lg text-xs font-semibold bg-indigo-600 border border-indigo-400',
    themeButton: 'px-2.5 py-1.5 rounded-lg text-sm bg-blue-700 border border-blue-500',
    main: 'max-w-6xl mx-auto px-4 pb-8',
  },
  section: {
    surface: 'mb-4 rounded-xl border border-slate-200 bg-white p-6 shadow dark:border-slate-700 dark:bg-slate-800',
    title: 'text-xl font-bold',
    description: 'mt-2 text-sm text-slate-500 dark:text-slate-400',
    controls: 'mt-3 flex flex-wrap gap-2',
    grid: 'grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3',
  },
  panel: {
    surface: 'rounded-3xl border border-slate-200 bg-white p-6 shadow dark:border-slate-700 dark:bg-slate-800',
    muted: 'rounded-3xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900',
    info: 'rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm dark:border-amber-700 dark:bg-amber-900/20',
    accent: 'rounded-2xl border border-blue-200 bg-blue-50 p-5 shadow-sm dark:border-blue-900/40 dark:bg-blue-950/40',
    tip: 'rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm dark:border-slate-700 dark:bg-slate-900',
  },
  modal: {
    overlay: 'fixed inset-0 z-50 flex items-start justify-center bg-black/50 p-4 backdrop-blur-sm',
    dialog: 'relative mt-[5%] w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl dark:bg-slate-800 dark:text-slate-100',
    close: 'absolute right-4 top-3 text-2xl text-slate-400 hover:text-slate-800 dark:hover:text-white',
  },
  card: {
    surface: 'rounded-xl border border-slate-200 bg-white p-4 shadow-sm transition hover:border-blue-300 dark:border-slate-700 dark:bg-slate-800',
    badge: 'w-10 text-center text-xl sm:text-2xl font-bold text-blue-600 dark:text-blue-400',
    title: 'text-lg font-bold text-slate-900 dark:text-slate-100',
    line: 'mt-1 text-sm text-slate-500 dark:text-slate-400',
    footer: 'mt-1 text-[11px] text-slate-400 dark:text-slate-400',
    note: 'mt-2 text-[11px] font-medium text-blue-600 dark:text-blue-400',
  },
  input: 'w-full rounded-lg border border-slate-300 bg-white p-3 text-base text-slate-900 outline-none transition focus:border-blue-400 focus:ring-2 focus:ring-blue-200 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100 dark:focus:border-blue-500 dark:focus:ring-blue-900/40',
  button: {
    primary: 'rounded-lg bg-blue-600 px-4 py-3 text-base font-semibold text-white shadow-sm transition hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50',
    secondary: 'rounded-lg bg-slate-200 px-4 py-3 text-base font-semibold text-slate-900 shadow-sm transition hover:bg-slate-300 disabled:cursor-not-allowed disabled:opacity-50 dark:bg-slate-700 dark:text-slate-100 dark:hover:bg-slate-600',
    danger: 'rounded-lg bg-red-600 px-4 py-3 text-base font-semibold text-white shadow-sm transition hover:bg-red-700 disabled:cursor-not-allowed disabled:opacity-50',
    icon: 'rounded-lg bg-blue-50 px-3 py-2 text-base text-blue-600 transition hover:bg-blue-100 disabled:cursor-not-allowed disabled:opacity-50 dark:bg-blue-900/50 dark:text-blue-300 dark:hover:bg-blue-800',
    pill: 'rounded-xl border-2 border-slate-200 px-4 py-3 text-base font-semibold transition hover:border-blue-500 disabled:cursor-not-allowed disabled:opacity-50 dark:border-slate-600',
    toggleActive: 'rounded-lg bg-white px-4 py-3 text-base font-semibold text-blue-600 shadow dark:bg-slate-700 dark:text-blue-300',
    toggleInactive: 'rounded-lg bg-slate-200 px-4 py-3 text-base font-semibold text-slate-700 transition hover:bg-slate-300 dark:bg-slate-700 dark:text-slate-200 dark:hover:bg-slate-600',
  },
};