/**
 * scripts/genSeedSql.ts
 *
 * One-off generator: emits supabase/migrations/012_seed_content_items.sql
 * containing (a) the idempotent DDL for public.content_items + the
 * get_content_items RPC (mirrors migration 011) and (b) INSERT statements for
 * every embedded curriculum pool from ./poolsData.ts.
 *
 * Run: npx tsx scripts/genSeedSql.ts
 * Apply: paste the generated file into Supabase Dashboard -> SQL Editor -> Run,
 *        or `supabase db push` once authenticated.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  ALPHABET,
  NUMBERS,
  GREETINGS,
  CALENDAR,
  VOCAB,
  GRAMMAR_DRILLS,
  ROLEPLAY,
  DICTATION,
  STORIES,
  RAPID_FIRE,
  SPELLING,
  PRONUNCIATION_TIPS,
} from './poolsData';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(__dirname, '../supabase/migrations/012_seed_content_items.sql');

interface Row {
  id: string;
  content_type: string;
  payload: unknown;
  sort: number;
}

/** Dollar-quote the JSON payload so no escaping is ever needed. */
function sqlRow(r: Row): string {
  const json = JSON.stringify(r.payload);
  return `('${r.id.replace(/'/g, "''")}', '${r.content_type}', $json$${json}$json$::jsonb, ${r.sort})`;
}

function buildRows(): Row[] {
  const rows: Row[] = [];
  ALPHABET.forEach((item, i) => rows.push({ id: `letter-${item.id}`, content_type: 'alphabet-item', payload: item, sort: i }));
  NUMBERS.forEach((item, i) => rows.push({ id: `number-${item.n}`, content_type: 'number-item', payload: item, sort: i }));
  GREETINGS.forEach((item, i) => rows.push({ id: `greeting-${item.de}`, content_type: 'greeting-item', payload: item, sort: i }));
  CALENDAR.forEach((item, i) => rows.push({ id: `calendar-${item.de}`, content_type: 'calendar-item', payload: item, sort: i }));
  VOCAB.forEach((item) => rows.push({ id: `vocab-${item.id}`, content_type: 'vocab-item', payload: item, sort: 0 }));
  Object.entries(GRAMMAR_DRILLS).forEach(([category, drills]) => {
    drills.forEach((d, i) => rows.push({ id: `grammar-${category}-${i}`, content_type: 'grammar-drill', payload: { ...d, category }, sort: i }));
  });
  ROLEPLAY.forEach((s, i) => rows.push({ id: `roleplay-${s.id}`, content_type: 'roleplay-scenario', payload: s, sort: i }));
  DICTATION.forEach((w, i) => rows.push({ id: `dictation-${w.word}`, content_type: 'dictation-word', payload: w, sort: i }));
  STORIES.forEach((story) => {
    story.sentences.forEach((s, i) =>
      rows.push({
        id: `${story.id}-${s.id}`,
        content_type: 'story-sentence',
        payload: { storyId: story.id, title: story.title, titleNe: story.titleNe, titleEn: story.titleEn, level: story.level, sentence: s },
        sort: i,
      })
    );
  });
  Object.values(RAPID_FIRE).forEach((questions) => {
    questions.forEach((q, i) => rows.push({ id: `rapid-${(q as { id: string }).id}`, content_type: 'rapidfire-question', payload: q, sort: i }));
  });
  Object.entries(SPELLING).forEach(([difficulty, words]) => {
    words.forEach((w, i) => rows.push({ id: `spelling-${difficulty}-${w.word}`, content_type: 'spelling-word', payload: { ...w, difficulty }, sort: i }));
  });
  Object.entries(PRONUNCIATION_TIPS).forEach(([letterId, tip]) => {
    rows.push({ id: `pron-tip-${letterId}`, content_type: 'pronunciation-tip', payload: { letterId, ...tip }, sort: 0 });
  });
  return rows;
}

function main(): void {
  const rows = buildRows();

  // Group inserts by content_type into one multi-row statement each.
  const byType = new Map<string, Row[]>();
  for (const r of rows) {
    const list = byType.get(r.content_type);
    if (list) list.push(r);
    else byType.set(r.content_type, [r]);
  }

  const parts: string[] = [];
  parts.push(`-- Migration: 012_seed_content_items.sql
--
-- Self-contained seed for the dynamic LessonEngine content pools.
-- Includes the idempotent DDL from migration 011 (safe to re-run) plus every
-- curriculum pool row. Apply via Supabase Dashboard -> SQL Editor -> Run,
-- or \`supabase db push\` once authenticated.
--
-- Generated by scripts/genSeedSql.ts — do not edit by hand.

-- ── DDL (idempotent; mirrors 011_content_items.sql) ────────────────────────

CREATE TABLE IF NOT EXISTS public.content_items (
    id TEXT PRIMARY KEY,
    content_type TEXT NOT NULL,
    payload JSONB NOT NULL,
    sort INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (content_type, id)
);
CREATE INDEX IF NOT EXISTS idx_content_items_type ON public.content_items(content_type);
CREATE INDEX IF NOT EXISTS idx_content_items_type_sort ON public.content_items(content_type, sort);

ALTER TABLE public.content_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read access for content_items" ON public.content_items;
CREATE POLICY "Public read access for content_items"
  ON public.content_items FOR SELECT USING (true);

CREATE OR REPLACE FUNCTION public.get_content_items(
  p_content_type TEXT,
  p_limit INT DEFAULT 200,
  p_shuffle BOOLEAN DEFAULT true
)
RETURNS SETOF public.content_items
LANGUAGE sql
STABLE
AS $$
  SELECT *
  FROM public.content_items
  WHERE content_type = p_content_type
  ORDER BY CASE WHEN p_shuffle THEN random() ELSE 0 END, sort
  LIMIT GREATEST(LEAST(COALESCE(p_limit, 200), 1000), 1);
$$;
GRANT EXECUTE ON FUNCTION public.get_content_items(TEXT, INT, BOOLEAN) TO anon, authenticated;

-- ── Seed data (${rows.length} rows across ${byType.size} pools) ───────────────────────────────────
`);

  for (const [type, typeRows] of byType) {
    parts.push(`-- ${type} (${typeRows.length} rows)`);
    parts.push(
      `INSERT INTO public.content_items (id, content_type, payload, sort) VALUES\n` +
        typeRows.map(sqlRow).join(',\n') +
        `\nON CONFLICT (content_type, id) DO UPDATE SET payload = EXCLUDED.payload, sort = EXCLUDED.sort;\n`
    );
  }

  fs.writeFileSync(OUT, parts.join('\n'), 'utf8');
  console.log(`[genSeedSql] wrote ${OUT} (${rows.length} rows, ${byType.size} pools)`);
}

main();