-- Migration: 012_seed_content_items.sql
--
-- Self-contained seed for the dynamic LessonEngine content pools.
-- Includes the idempotent DDL from migration 011 (safe to re-run) plus every
-- curriculum pool row. Apply via Supabase Dashboard -> SQL Editor -> Run,
-- or `supabase db push` once authenticated.
--
-- Generated by scripts/genSeedSql.ts — do not edit by hand.

-- ── DDL (idempotent; mirrors 011_content_items.sql) ────────────────────────

CREATE TABLE IF NOT EXISTS public.content_items (
    id TEXT PRIMARY KEY,
    content_type TEXT NOT NULL,
    payload JSONB NOT NULL,
    sort INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (content_type, id)
);
CREATE INDEX IF NOT EXISTS idx_content_items_type ON public.content_items(content_type);
CREATE INDEX IF NOT EXISTS idx_content_items_type_sort ON public.content_items(content_type, sort);

ALTER TABLE public.content_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read access for content_items" ON public.content_items;
CREATE POLICY "Public read access for content_items"
  ON public.content_items FOR SELECT USING (true);

CREATE OR REPLACE FUNCTION public.get_content_items(
  p_content_type TEXT,
  p_limit INT DEFAULT 200,
  p_shuffle BOOLEAN DEFAULT true
)
RETURNS SETOF public.content_items
LANGUAGE sql
STABLE
AS $$
  SELECT *
  FROM public.content_items
  WHERE content_type = p_content_type
  ORDER BY CASE WHEN p_shuffle THEN random() ELSE 0 END, sort
  LIMIT GREATEST(LEAST(COALESCE(p_limit, 200), 1000), 1);
$$;
GRANT EXECUTE ON FUNCTION public.get_content_items(TEXT, INT, BOOLEAN) TO anon, authenticated;

-- ── Seed data (200 rows across 12 pools) ───────────────────────────────────

-- alphabet-item (30 rows)
INSERT INTO public.content_items (id, content_type, payload, sort) VALUES
('letter-A', 'alphabet-item', $json${"id":"A","letter":"A a","gerPhonetic":"Ah","engPhonetic":"Ah","nepPhonetic":"आ","type":"vowel","category":"standard","example":"Apfel","exampleFull":"Apfel (Apple / स्याउ)","speak":"A","speakWord":"Apfel"}$json$::jsonb, 0),
('letter-B', 'alphabet-item', $json${"id":"B","letter":"B b","gerPhonetic":"Be","engPhonetic":"Bay","nepPhonetic":"बे","type":"consonant","category":"standard","example":"Buch","exampleFull":"Buch (Book / किताब)","speak":"B","speakWord":"Buch"}$json$::jsonb, 1),
('letter-C', 'alphabet-item', $json${"id":"C","letter":"C c","gerPhonetic":"Ce","engPhonetic":"Tsay","nepPhonetic":"त्से","type":"consonant","category":"standard","example":"Computer","exampleFull":"Computer (Computer / कम्प्युटर)","speak":"C","speakWord":"Computer"}$json$::jsonb, 2),
('letter-D', 'alphabet-item', $json${"id":"D","letter":"D d","gerPhonetic":"De","engPhonetic":"Day","nepPhonetic":"डे","type":"consonant","category":"standard","example":"Danke","exampleFull":"Danke (Thanks / धन्यवाद)","speak":"D","speakWord":"Danke"}$json$::jsonb, 3),
('letter-E', 'alphabet-item', $json${"id":"E","letter":"E e","gerPhonetic":"E","engPhonetic":"Ay","nepPhonetic":"ए","type":"vowel","category":"standard","example":"Elefant","exampleFull":"Elefant (Elephant / हात्ती)","speak":"E","speakWord":"Elefant"}$json$::jsonb, 4),
('letter-F', 'alphabet-item', $json${"id":"F","letter":"F f","gerPhonetic":"Eff","engPhonetic":"Eff","nepPhonetic":"एफ्","type":"consonant","category":"standard","example":"Fisch","exampleFull":"Fisch (Fish / माछा)","speak":"F","speakWord":"Fisch"}$json$::jsonb, 5),
('letter-G', 'alphabet-item', $json${"id":"G","letter":"G g","gerPhonetic":"Ge","engPhonetic":"Gay","nepPhonetic":"गे","type":"consonant","category":"standard","example":"Gut","exampleFull":"Gut (Good / राम्रो)","speak":"G","speakWord":"Gut"}$json$::jsonb, 6),
('letter-H', 'alphabet-item', $json${"id":"H","letter":"H h","gerPhonetic":"Ha","engPhonetic":"Hah","nepPhonetic":"हा","type":"consonant","category":"standard","example":"Haus","exampleFull":"Haus (House / घर)","speak":"H","speakWord":"Haus"}$json$::jsonb, 7),
('letter-I', 'alphabet-item', $json${"id":"I","letter":"I i","gerPhonetic":"I","engPhonetic":"Ee","nepPhonetic":"ई","type":"vowel","category":"standard","example":"Igel","exampleFull":"Igel (Hedgehog / दुम्सी)","speak":"I","speakWord":"Igel"}$json$::jsonb, 8),
('letter-J', 'alphabet-item', $json${"id":"J","letter":"J j","gerPhonetic":"Jot","engPhonetic":"Yot","nepPhonetic":"योट्","type":"consonant","category":"standard","example":"Ja","exampleFull":"Ja (Yes / हो)","speak":"J","speakWord":"Ja"}$json$::jsonb, 9),
('letter-K', 'alphabet-item', $json${"id":"K","letter":"K k","gerPhonetic":"Ka","engPhonetic":"Kah","nepPhonetic":"का","type":"consonant","category":"standard","example":"Kaffee","exampleFull":"Kaffee (Coffee / कफी)","speak":"K","speakWord":"Kaffee"}$json$::jsonb, 10),
('letter-L', 'alphabet-item', $json${"id":"L","letter":"L l","gerPhonetic":"Ell","engPhonetic":"Ell","nepPhonetic":"एल्","type":"consonant","category":"standard","example":"Lampe","exampleFull":"Lampe (Lamp / बत्ती)","speak":"L","speakWord":"Lampe"}$json$::jsonb, 11),
('letter-M', 'alphabet-item', $json${"id":"M","letter":"M m","gerPhonetic":"Emm","engPhonetic":"Emm","nepPhonetic":"एम्","type":"consonant","category":"standard","example":"Mutter","exampleFull":"Mutter (Mother / आमा)","speak":"M","speakWord":"Mutter"}$json$::jsonb, 12),
('letter-N', 'alphabet-item', $json${"id":"N","letter":"N n","gerPhonetic":"Enn","engPhonetic":"Enn","nepPhonetic":"एन्","type":"consonant","category":"standard","example":"Name","exampleFull":"Name (Name / नाम)","speak":"N","speakWord":"Name"}$json$::jsonb, 13),
('letter-O', 'alphabet-item', $json${"id":"O","letter":"O o","gerPhonetic":"O","engPhonetic":"Oh","nepPhonetic":"ओ","type":"vowel","category":"standard","example":"Orange","exampleFull":"Orange (Orange / सुन्तला)","speak":"O","speakWord":"Orange"}$json$::jsonb, 14),
('letter-P', 'alphabet-item', $json${"id":"P","letter":"P p","gerPhonetic":"Pe","engPhonetic":"Pay","nepPhonetic":"पे","type":"consonant","category":"standard","example":"Papa","exampleFull":"Papa (Dad / बाबा)","speak":"P","speakWord":"Papa"}$json$::jsonb, 15),
('letter-Q', 'alphabet-item', $json${"id":"Q","letter":"Q q","gerPhonetic":"Ku","engPhonetic":"Koo","nepPhonetic":"कु","type":"consonant","category":"standard","example":"Quelle","exampleFull":"Quelle (Source / मुहान)","speak":"Q","speakWord":"Quelle"}$json$::jsonb, 16),
('letter-R', 'alphabet-item', $json${"id":"R","letter":"R r","gerPhonetic":"Err","engPhonetic":"Err","nepPhonetic":"एर","type":"consonant","category":"standard","example":"Rot","exampleFull":"Rot (Red / रातो)","speak":"R","speakWord":"Rot"}$json$::jsonb, 17),
('letter-S', 'alphabet-item', $json${"id":"S","letter":"S s","gerPhonetic":"Ess","engPhonetic":"Ess","nepPhonetic":"एस्","type":"consonant","category":"standard","example":"Sonne","exampleFull":"Sonne (Sun / घाम)","speak":"S","speakWord":"Sonne"}$json$::jsonb, 18),
('letter-T', 'alphabet-item', $json${"id":"T","letter":"T t","gerPhonetic":"Te","engPhonetic":"Tay","nepPhonetic":"टे","type":"consonant","category":"standard","example":"Tee","exampleFull":"Tee (Tea / चिया)","speak":"T","speakWord":"Tee"}$json$::jsonb, 19),
('letter-U', 'alphabet-item', $json${"id":"U","letter":"U u","gerPhonetic":"U","engPhonetic":"Oo","nepPhonetic":"ऊ","type":"vowel","category":"standard","example":"Uhr","exampleFull":"Uhr (Clock / घडी)","speak":"U","speakWord":"Uhr"}$json$::jsonb, 20),
('letter-V', 'alphabet-item', $json${"id":"V","letter":"V v","gerPhonetic":"Fau","engPhonetic":"Fow (like F)","nepPhonetic":"फाउ","type":"consonant","category":"standard","example":"Vater","exampleFull":"Vater (Father / बुबा)","speak":"V","speakWord":"Vater"}$json$::jsonb, 21),
('letter-W', 'alphabet-item', $json${"id":"W","letter":"W w","gerPhonetic":"We","engPhonetic":"Vay (like V)","nepPhonetic":"भे","type":"consonant","category":"standard","example":"Wasser","exampleFull":"Wasser (Water / पानी)","speak":"W","speakWord":"Wasser"}$json$::jsonb, 22),
('letter-X', 'alphabet-item', $json${"id":"X","letter":"X x","gerPhonetic":"Iks","engPhonetic":"Iks","nepPhonetic":"इक्स्","type":"consonant","category":"standard","example":"Xylophon","exampleFull":"Xylophon (Xylophone)","speak":"X","speakWord":"Xylophon"}$json$::jsonb, 23),
('letter-Y', 'alphabet-item', $json${"id":"Y","letter":"Y y","gerPhonetic":"Ypsilon","engPhonetic":"Ipsilon","nepPhonetic":"इप्सिलन","type":"consonant","category":"standard","example":"Yoga","exampleFull":"Yoga (Yoga / योग)","speak":"Y","speakWord":"Yoga"}$json$::jsonb, 24),
('letter-Z', 'alphabet-item', $json${"id":"Z","letter":"Z z","gerPhonetic":"Zett","engPhonetic":"Tset","nepPhonetic":"त्सेट्","type":"consonant","category":"standard","example":"Zug","exampleFull":"Zug (Train / रेल)","speak":"Z","speakWord":"Zug"}$json$::jsonb, 25),
('letter-Ae', 'alphabet-item', $json${"id":"Ae","letter":"Ä ä","gerPhonetic":"A-Umlaut","engPhonetic":"Eh","nepPhonetic":"ए (छोटो)","type":"vowel","category":"special","example":"Äpfel","exampleFull":"Äpfel (Apples / स्याउहरू)","speak":"Ä","speakWord":"Äpfel"}$json$::jsonb, 26),
('letter-Oe', 'alphabet-item', $json${"id":"Oe","letter":"Ö ö","gerPhonetic":"O-Umlaut","engPhonetic":"Uuh","nepPhonetic":"अ / ओ","type":"vowel","category":"special","example":"Öl","exampleFull":"Öl (Oil / तेल)","speak":"Ö","speakWord":"Öl"}$json$::jsonb, 27),
('letter-Ue', 'alphabet-item', $json${"id":"Ue","letter":"Ü ü","gerPhonetic":"U-Umlaut","engPhonetic":"Eww","nepPhonetic":"उइ / इ","type":"vowel","category":"special","example":"Über","exampleFull":"Über (Over / माथि)","speak":"Ü","speakWord":"Über"}$json$::jsonb, 28),
('letter-Sz', 'alphabet-item', $json${"id":"Sz","letter":"ß","gerPhonetic":"Eszett","engPhonetic":"Sharp S","nepPhonetic":"एस्-त्सेट्","type":"consonant","category":"special","example":"Straße","exampleFull":"Straße (Street / सडक)","speak":"ß","speakWord":"Straße"}$json$::jsonb, 29)
ON CONFLICT (content_type, id) DO UPDATE SET payload = EXCLUDED.payload, sort = EXCLUDED.sort;

-- number-item (39 rows)
INSERT INTO public.content_items (id, content_type, payload, sort) VALUES
('number-0', 'number-item', $json${"n":0,"de":"null","engPh":"nool","nepPh":"नुल्","en":"zero","ne":"शून्य"}$json$::jsonb, 0),
('number-1', 'number-item', $json${"n":1,"de":"eins","engPh":"ine-ss","nepPh":"आइन्स्","en":"one","ne":"एक"}$json$::jsonb, 1),
('number-2', 'number-item', $json${"n":2,"de":"zwei","engPh":"tsvy","nepPh":"त्स्वाइ","en":"two","ne":"दुई"}$json$::jsonb, 2),
('number-3', 'number-item', $json${"n":3,"de":"drei","engPh":"dry","nepPh":"द्राई","en":"three","ne":"तीन"}$json$::jsonb, 3),
('number-4', 'number-item', $json${"n":4,"de":"vier","engPh":"feer","nepPh":"फीअर","en":"four","ne":"चार"}$json$::jsonb, 4),
('number-5', 'number-item', $json${"n":5,"de":"fünf","engPh":"fuenf","nepPh":"फ्युन्फ्","en":"five","ne":"पाँच"}$json$::jsonb, 5),
('number-6', 'number-item', $json${"n":6,"de":"sechs","engPh":"zex","nepPh":"ज़ेक्स","en":"six","ne":"छ"}$json$::jsonb, 6),
('number-7', 'number-item', $json${"n":7,"de":"sieben","engPh":"zee-ben","nepPh":"ज़ीबेन्","en":"seven","ne":"सात"}$json$::jsonb, 7),
('number-8', 'number-item', $json${"n":8,"de":"acht","engPh":"ahkt","nepPh":"आख्त्","en":"eight","ne":"आठ"}$json$::jsonb, 8),
('number-9', 'number-item', $json${"n":9,"de":"neun","engPh":"noin","nepPh":"नोइन्","en":"nine","ne":"नौ"}$json$::jsonb, 9),
('number-10', 'number-item', $json${"n":10,"de":"zehn","engPh":"tsayn","nepPh":"त्सेन्","en":"ten","ne":"दश"}$json$::jsonb, 10),
('number-11', 'number-item', $json${"n":11,"de":"elf","engPh":"elf","nepPh":"एल्फ्","en":"eleven","ne":"एघार"}$json$::jsonb, 11),
('number-12', 'number-item', $json${"n":12,"de":"zwölf","engPh":"tsvurf","nepPh":"त्स्वोल्फ्","en":"twelve","ne":"बाह्र"}$json$::jsonb, 12),
('number-13', 'number-item', $json${"n":13,"de":"dreizehn","engPh":"dry-tsayn","nepPh":"द्राई-त्सेन्","en":"thirteen","ne":"तेरह","note":"drei + zehn"}$json$::jsonb, 13),
('number-14', 'number-item', $json${"n":14,"de":"vierzehn","engPh":"feer-tsayn","nepPh":"फीअर-त्सेन्","en":"fourteen","ne":"चौध","note":"vier + zehn"}$json$::jsonb, 14),
('number-15', 'number-item', $json${"n":15,"de":"fünfzehn","engPh":"fuenf-tsayn","nepPh":"फ्युन्फ्-त्सेन्","en":"fifteen","ne":"पन्ध्र","note":"fünf + zehn"}$json$::jsonb, 15),
('number-16', 'number-item', $json${"n":16,"de":"sechzehn","engPh":"zex-tsayn","nepPh":"ज़ेक्स-त्सेन्","en":"sixteen","ne":"सोह्र","note":"sechs + zehn"}$json$::jsonb, 16),
('number-17', 'number-item', $json${"n":17,"de":"siebzehn","engPh":"zeep-tsayn","nepPh":"ज़ीब्-त्सेन्","en":"seventeen","ne":"सत्र","note":"sieben + zehn"}$json$::jsonb, 17),
('number-18', 'number-item', $json${"n":18,"de":"achtzehn","engPh":"ahkt-tsayn","nepPh":"आख्त्-त्सेन्","en":"eighteen","ne":"अठार","note":"acht + zehn"}$json$::jsonb, 18),
('number-19', 'number-item', $json${"n":19,"de":"neunzehn","engPh":"noin-tsayn","nepPh":"नोइन्-त्सेन्","en":"nineteen","ne":"उन्नाइस","note":"neun + zehn"}$json$::jsonb, 19),
('number-20', 'number-item', $json${"n":20,"de":"zwanzig","engPh":"tsvahn-tsikh","nepPh":"त्स्वान्-त्सिख्","en":"twenty","ne":"बीस","note":"base tens"}$json$::jsonb, 20),
('number-21', 'number-item', $json${"n":21,"de":"einundzwanzig","engPh":"ine-oont-tsvahn-tsikh","nepPh":"आइन्-उन्ड्-त्स्वान्त्सिख्","en":"twenty-one","ne":"एक्काइस","note":"eins + und + zwanzig"}$json$::jsonb, 21),
('number-22', 'number-item', $json${"n":22,"de":"zweiundzwanzig","engPh":"tsvy-oont-tsvahn-tsikh","nepPh":"त्स्वाइ-उन्ड्-त्स्वान्त्सिख्","en":"twenty-two","ne":"बाइस","note":"zwei + und + zwanzig"}$json$::jsonb, 22),
('number-30', 'number-item', $json${"n":30,"de":"dreißig","engPh":"dry-sikh","nepPh":"द्राई-सिख्","en":"thirty","ne":"तीस","note":"drei + ßig"}$json$::jsonb, 23),
('number-33', 'number-item', $json${"n":33,"de":"dreiunddreißig","engPh":"dry-oont-dry-sikh","nepPh":"द्राई-उन्ड्-द्राईसिख्","en":"thirty-three","ne":"तैंतीस","note":"drei + und + dreißig"}$json$::jsonb, 24),
('number-40', 'number-item', $json${"n":40,"de":"vierzig","engPh":"feer-tsikh","nepPh":"फीअर-त्सिख्","en":"forty","ne":"चालीस","note":"vier + zig"}$json$::jsonb, 25),
('number-45', 'number-item', $json${"n":45,"de":"fünfundvierzig","engPh":"fuenf-oont-feer-tsikh","nepPh":"फ्युन्फ्-उन्ड्-फीअर्त्सिख्","en":"forty-five","ne":"पैंतालीस","note":"fünf + und + vierzig"}$json$::jsonb, 26),
('number-50', 'number-item', $json${"n":50,"de":"fünfzig","engPh":"fuenf-tsikh","nepPh":"फ्युन्फ्-त्सिख्","en":"fifty","ne":"पचास","note":"fünf + zig"}$json$::jsonb, 27),
('number-60', 'number-item', $json${"n":60,"de":"sechzig","engPh":"zex-tsikh","nepPh":"ज़ेक्स-त्सिख्","en":"sixty","ne":"साठी","note":"sechs + zig"}$json$::jsonb, 28),
('number-70', 'number-item', $json${"n":70,"de":"siebzig","engPh":"zeep-tsikh","nepPh":"ज़ीब्-त्सिख्","en":"seventy","ne":"सत्तरी","note":"sieben + zig"}$json$::jsonb, 29),
('number-80', 'number-item', $json${"n":80,"de":"achtzig","engPh":"ahkt-tsikh","nepPh":"आख्त्-त्सिख्","en":"eighty","ne":"अस्सी","note":"acht + zig"}$json$::jsonb, 30),
('number-90', 'number-item', $json${"n":90,"de":"neunzig","engPh":"noin-tsikh","nepPh":"नोइन्-त्सिख्","en":"ninety","ne":"नब्बे","note":"neun + zig"}$json$::jsonb, 31),
('number-99', 'number-item', $json${"n":99,"de":"neunundneunzig","engPh":"noin-oont-noin-tsikh","nepPh":"नोइन्-उन्ड्-नोइन्त्सिख्","en":"ninety-nine","ne":"निन्यानबे","note":"neun + und + neunzig"}$json$::jsonb, 32),
('number-100', 'number-item', $json${"n":100,"de":"hundert","engPh":"hoon-dert","nepPh":"हुन्डर्त्","en":"one hundred","ne":"एक सय","note":"100 = hundert"}$json$::jsonb, 33),
('number-101', 'number-item', $json${"n":101,"de":"hunderteins","engPh":"hoon-dert-ine-ss","nepPh":"हुन्डर्त्-आइन्स्","en":"one hundred one","ne":"एक सय एक","note":"hundert + eins"}$json$::jsonb, 34),
('number-200', 'number-item', $json${"n":200,"de":"zweihundert","engPh":"tsvy-hoon-dert","nepPh":"त्स्वाइ-हुन्डर्त्","en":"two hundred","ne":"दुई सय","note":"zwei + hundert"}$json$::jsonb, 35),
('number-1000', 'number-item', $json${"n":1000,"de":"tausend","engPh":"tow-zent","nepPh":"ताउज़ेन्ट्","en":"one thousand","ne":"एक हजार","note":"1000 = tausend"}$json$::jsonb, 36),
('number-2000', 'number-item', $json${"n":2000,"de":"zweitausend","engPh":"tsvy-tow-zent","nepPh":"त्स्वाइ-ताउज़ेन्ट्","en":"two thousand","ne":"दुई हजार","note":"zwei + tausend"}$json$::jsonb, 37),
('number-1000000', 'number-item', $json${"n":1000000,"de":"eine Million","engPh":"ine-eh mil-yohn","nepPh":"आइने मिल्योन्","en":"one million","ne":"एक लाख","note":"1,000,000 = eine Million"}$json$::jsonb, 38)
ON CONFLICT (content_type, id) DO UPDATE SET payload = EXCLUDED.payload, sort = EXCLUDED.sort;

-- greeting-item (8 rows)
INSERT INTO public.content_items (id, content_type, payload, sort) VALUES
('greeting-Hallo', 'greeting-item', $json${"de":"Hallo","engPh":"hah-lo","nepPh":"हालो","en":"Hello","ne":"नमस्ते"}$json$::jsonb, 0),
('greeting-Guten Morgen', 'greeting-item', $json${"de":"Guten Morgen","engPh":"goo-ten mor-gen","nepPh":"गुटेन मोर्गेन","en":"Good Morning","ne":"शुभ प्रभात"}$json$::jsonb, 1),
('greeting-Guten Tag', 'greeting-item', $json${"de":"Guten Tag","engPh":"goo-ten tahk","nepPh":"गुटेन टाक","en":"Good Day","ne":"नमस्कार"}$json$::jsonb, 2),
('greeting-Guten Abend', 'greeting-item', $json${"de":"Guten Abend","engPh":"goo-ten ah-bent","nepPh":"गुटेन आबेन्ट","en":"Good Evening","ne":"शुभ साँझ"}$json$::jsonb, 3),
('greeting-Auf Wiedersehen', 'greeting-item', $json${"de":"Auf Wiedersehen","engPh":"owf vee-der-zayn","nepPh":"आउफ विडरजेन","en":"Goodbye","ne":"फेरि भेटौंला"}$json$::jsonb, 4),
('greeting-Danke', 'greeting-item', $json${"de":"Danke","engPh":"dahn-kuh","nepPh":"डानके","en":"Thank you","ne":"धन्यवाद"}$json$::jsonb, 5),
('greeting-Bitte', 'greeting-item', $json${"de":"Bitte","engPh":"bih-tuh","nepPh":"बिट्टे","en":"Please / You are welcome","ne":"कृपया / स्वागत छ"}$json$::jsonb, 6),
('greeting-Entschuldigung', 'greeting-item', $json${"de":"Entschuldigung","engPh":"ent-shul-di-gung","nepPh":"एन्टशुल्डिगुङ","en":"Excuse me / Sorry","ne":"माफ गर्नुहोस्"}$json$::jsonb, 7)
ON CONFLICT (content_type, id) DO UPDATE SET payload = EXCLUDED.payload, sort = EXCLUDED.sort;

-- calendar-item (19 rows)
INSERT INTO public.content_items (id, content_type, payload, sort) VALUES
('calendar-Montag', 'calendar-item', $json${"de":"Montag","engPh":"mohn-tak","nepPh":"मोन्-टाक","en":"Monday","ne":"सोमबार"}$json$::jsonb, 0),
('calendar-Dienstag', 'calendar-item', $json${"de":"Dienstag","engPh":"deen-stak","nepPh":"डिन्स्ताक","en":"Tuesday","ne":"मंगलबार"}$json$::jsonb, 1),
('calendar-Mittwoch', 'calendar-item', $json${"de":"Mittwoch","engPh":"mitt-vok","nepPh":"मित्त्वोख","en":"Wednesday","ne":"बुधबार"}$json$::jsonb, 2),
('calendar-Donnerstag', 'calendar-item', $json${"de":"Donnerstag","engPh":"don-ner-shtahk","nepPh":"डोनरश्ताक","en":"Thursday","ne":"बिहिबार"}$json$::jsonb, 3),
('calendar-Freitag', 'calendar-item', $json${"de":"Freitag","engPh":"fray-tahk","nepPh":"फ्राइटाक","en":"Friday","ne":"शुक्रबार"}$json$::jsonb, 4),
('calendar-Samstag', 'calendar-item', $json${"de":"Samstag","engPh":"zahm-stahk","nepPh":"ज़ामसताक","en":"Saturday","ne":"शनिबार"}$json$::jsonb, 5),
('calendar-Sonntag', 'calendar-item', $json${"de":"Sonntag","engPh":"zohn-tahk","nepPh":"ज़ोनताक","en":"Sunday","ne":"आइतबार"}$json$::jsonb, 6),
('calendar-Januar', 'calendar-item', $json${"de":"Januar","engPh":"yah-noo-ahr","nepPh":"जानुअर","en":"January","ne":"जनवरी"}$json$::jsonb, 7),
('calendar-Februar', 'calendar-item', $json${"de":"Februar","engPh":"fay-broo-ahr","nepPh":"फेब्रुअर","en":"February","ne":"फेब्रुअरी"}$json$::jsonb, 8),
('calendar-März', 'calendar-item', $json${"de":"März","engPh":"maertz","nepPh":"मेर्स","en":"March","ne":"मार्च"}$json$::jsonb, 9),
('calendar-April', 'calendar-item', $json${"de":"April","engPh":"ah-pril","nepPh":"एप्रिल","en":"April","ne":"अप्रिल"}$json$::jsonb, 10),
('calendar-Mai', 'calendar-item', $json${"de":"Mai","engPh":"my","nepPh":"माई","en":"May","ne":"मे"}$json$::jsonb, 11),
('calendar-Juni', 'calendar-item', $json${"de":"Juni","engPh":"yoo-nee","nepPh":"जुनी","en":"June","ne":"जून"}$json$::jsonb, 12),
('calendar-Juli', 'calendar-item', $json${"de":"Juli","engPh":"yoo-lee","nepPh":"जुलाई","en":"July","ne":"जुलाई"}$json$::jsonb, 13),
('calendar-August', 'calendar-item', $json${"de":"August","engPh":"ow-goost","nepPh":"अगस्ट","en":"August","ne":"अगष्ट"}$json$::jsonb, 14),
('calendar-September', 'calendar-item', $json${"de":"September","engPh":"zep-tem-ber","nepPh":"सेप्टेम्बर","en":"September","ne":"सेप्टेम्बर"}$json$::jsonb, 15),
('calendar-Oktober', 'calendar-item', $json${"de":"Oktober","engPh":"ok-toh-ber","nepPh":"अक्टोबर","en":"October","ne":"अक्टोबर"}$json$::jsonb, 16),
('calendar-November', 'calendar-item', $json${"de":"November","engPh":"noh-vem-ber","nepPh":"नोभेम्बर","en":"November","ne":"नोभेम्बर"}$json$::jsonb, 17),
('calendar-Dezember', 'calendar-item', $json${"de":"Dezember","engPh":"day-tsem-ber","nepPh":"डे़ज़ेम्बर","en":"December","ne":"दिसेम्बर"}$json$::jsonb, 18)
ON CONFLICT (content_type, id) DO UPDATE SET payload = EXCLUDED.payload, sort = EXCLUDED.sort;

-- vocab-item (7 rows)
INSERT INTO public.content_items (id, content_type, payload, sort) VALUES
('vocab-fam-mutter', 'vocab-item', $json${"id":"fam-mutter","de":"Mutter","en":"mother","ne":"आमा","tags":["family"],"level":"A1","exampleDe":"Meine Mutter kocht."}$json$::jsonb, 0),
('vocab-food-ich', 'vocab-item', $json${"id":"food-ich","de":"Ich","en":"I","ne":"","tags":["food","A1"],"level":"A1"}$json$::jsonb, 0),
('vocab-genera-practice', 'vocab-item', $json${"id":"genera-practice","de":"Practice","en":"these","ne":"","tags":["general","A1"],"level":"A1"}$json$::jsonb, 0),
('vocab-health-auge', 'vocab-item', $json${"id":"health-auge","de":"Auge","en":"eye","ne":"","tags":["health","A1"],"level":"A1"}$json$::jsonb, 0),
('vocab-home-mit', 'vocab-item', $json${"id":"home-mit","de":"mit","en":"to","ne":"","tags":["home","A1"],"level":"A1"}$json$::jsonb, 0),
('vocab-leisur-amüsieren', 'vocab-item', $json${"id":"leisur-amüsieren","de":"amüsieren","en":"to","ne":"","tags":["leisure","A1"],"level":"A1"}$json$::jsonb, 0),
('vocab-travel-affe', 'vocab-item', $json${"id":"travel-affe","de":"Affe","en":"monkey","ne":"","tags":["travel","A1"],"level":"A1"}$json$::jsonb, 0)
ON CONFLICT (content_type, id) DO UPDATE SET payload = EXCLUDED.payload, sort = EXCLUDED.sort;

-- grammar-drill (20 rows)
INSERT INTO public.content_items (id, content_type, payload, sort) VALUES
('grammar-sein-0', 'grammar-drill', $json${"prompt":"Ich ___ Student.","options":["bin","bist","ist"],"correct":"bin","category":"sein"}$json$::jsonb, 0),
('grammar-sein-1', 'grammar-drill', $json${"prompt":"Du ___ nett.","options":["bin","bist","ist"],"correct":"bist","category":"sein"}$json$::jsonb, 1),
('grammar-sein-2', 'grammar-drill', $json${"prompt":"Er ___ müde.","options":["bin","bist","ist"],"correct":"ist","category":"sein"}$json$::jsonb, 2),
('grammar-sein-3', 'grammar-drill', $json${"prompt":"Wir ___ hier.","options":["sind","seid","ist"],"correct":"sind","category":"sein"}$json$::jsonb, 3),
('grammar-sein-4', 'grammar-drill', $json${"prompt":"Ihr ___ Freunde.","options":["sind","seid","bin"],"correct":"seid","category":"sein"}$json$::jsonb, 4),
('grammar-haben-0', 'grammar-drill', $json${"prompt":"Ich ___ ein Buch.","options":["habe","hast","hat"],"correct":"habe","category":"haben"}$json$::jsonb, 0),
('grammar-haben-1', 'grammar-drill', $json${"prompt":"Du ___ einen Stift.","options":["habe","hast","hat"],"correct":"hast","category":"haben"}$json$::jsonb, 1),
('grammar-haben-2', 'grammar-drill', $json${"prompt":"Sie ___ eine Schwester.","options":["habe","hast","hat"],"correct":"hat","category":"haben"}$json$::jsonb, 2),
('grammar-haben-3', 'grammar-drill', $json${"prompt":"Wir ___ Hunger.","options":["haben","habt","hat"],"correct":"haben","category":"haben"}$json$::jsonb, 3),
('grammar-haben-4', 'grammar-drill', $json${"prompt":"Ihr ___ Zeit.","options":["haben","habt","hast"],"correct":"habt","category":"haben"}$json$::jsonb, 4),
('grammar-weakVerb-0', 'grammar-drill', $json${"prompt":"Ich ___ Kaffee. (machen)","options":["mache","machst","macht"],"correct":"mache","category":"weakVerb"}$json$::jsonb, 0),
('grammar-weakVerb-1', 'grammar-drill', $json${"prompt":"Du ___ die Arbeit. (machen)","options":["mache","machst","macht"],"correct":"machst","category":"weakVerb"}$json$::jsonb, 1),
('grammar-weakVerb-2', 'grammar-drill', $json${"prompt":"Er ___ Sport. (machen)","options":["mache","machst","macht"],"correct":"macht","category":"weakVerb"}$json$::jsonb, 2),
('grammar-weakVerb-3', 'grammar-drill', $json${"prompt":"Wir ___ Musik. (machen)","options":["machen","macht","mache"],"correct":"machen","category":"weakVerb"}$json$::jsonb, 3),
('grammar-weakVerb-4', 'grammar-drill', $json${"prompt":"Ihr ___ Hausaufgaben. (machen)","options":["machen","macht","mache"],"correct":"macht","category":"weakVerb"}$json$::jsonb, 4),
('grammar-cases-0', 'grammar-drill', $json${"prompt":"Der Mann sieht ___ Frau. (who receives?)","options":["den Mann","die Frau"],"correct":"die Frau","category":"cases"}$json$::jsonb, 0),
('grammar-cases-1', 'grammar-drill', $json${"prompt":"Ich habe ___ Bruder. (direct object)","options":["einen","ein"],"correct":"einen","category":"cases"}$json$::jsonb, 1),
('grammar-cases-2', 'grammar-drill', $json${"prompt":"___ Tisch ist groß. (subject)","options":["Der","Den"],"correct":"Der","category":"cases"}$json$::jsonb, 2),
('grammar-cases-3', 'grammar-drill', $json${"prompt":"Wir kaufen ___ Buch. (direct object)","options":["das","die"],"correct":"das","category":"cases"}$json$::jsonb, 3),
('grammar-cases-4', 'grammar-drill', $json${"prompt":"Sie liebt ___ Hund. (direct object)","options":["einen","ein"],"correct":"einen","category":"cases"}$json$::jsonb, 4)
ON CONFLICT (content_type, id) DO UPDATE SET payload = EXCLUDED.payload, sort = EXCLUDED.sort;

-- roleplay-scenario (3 rows)
INSERT INTO public.content_items (id, content_type, payload, sort) VALUES
('roleplay-cafe', 'roleplay-scenario', $json${"id":"cafe","title":"Im Café","emoji":"☕","steps":[{"npc":"Guten Tag! Was möchten Sie?","prompt":"What do you order?","options":[{"text":"Ich hätte gern einen Kaffee, bitte.","ok":true,"fb":"Sehr gut!"},{"text":"Wo ist der Bahnhof?","ok":false,"fb":"That is directions, not an order."},{"text":"Ich bin müde.","ok":false,"fb":"True, but you still need to order!"}]},{"npc":"Möchten Sie auch etwas zu essen?","prompt":"What do you answer?","options":[{"text":"Nein, danke. Nur den Kaffee.","ok":true,"fb":"Perfekt!"},{"text":"Ich heiße Anna.","ok":false,"fb":"That is your name, not about food."}]}]}$json$::jsonb, 0),
('roleplay-intro', 'roleplay-scenario', $json${"id":"intro","title":"Vorstellung","emoji":"👋","steps":[{"npc":"Hallo! Wie heißt du?","prompt":"Introduce yourself.","options":[{"text":"Ich heiße Pramod. Und du?","ok":true,"fb":"Sehr gut!"},{"text":"Ich bin aus Nepal.","ok":false,"fb":"That answers origin, not name."}]},{"npc":"Woher kommst du?","prompt":"Answer where you are from.","options":[{"text":"Ich komme aus Nepal.","ok":true,"fb":"Perfekt!"},{"text":"Ich habe Hunger.","ok":false,"fb":"That is about hunger, not origin."}]}]}$json$::jsonb, 1),
('roleplay-hotel', 'roleplay-scenario', $json${"id":"hotel","title":"Hotel-Check-in","emoji":"🏨","steps":[{"npc":"Guten Abend. Haben Sie eine Reservierung?","prompt":"Answer the hotel clerk.","options":[{"text":"Ja, ich habe eine Reservierung.","ok":true,"fb":"Sehr gut!"},{"text":"Ich brauche ein Taxi.","ok":false,"fb":"A taxi is not a reservation."}]},{"npc":"Ihr Zimmer ist Nummer 12. Hier ist der Schlüssel.","prompt":"What do you say?","options":[{"text":"Vielen Dank!","ok":true,"fb":"Perfekt!"},{"text":"Auf Wiedersehen!","ok":false,"fb":"Thank the clerk first!"}]}]}$json$::jsonb, 2)
ON CONFLICT (content_type, id) DO UPDATE SET payload = EXCLUDED.payload, sort = EXCLUDED.sort;

-- dictation-word (12 rows)
INSERT INTO public.content_items (id, content_type, payload, sort) VALUES
('dictation-Hallo', 'dictation-word', $json${"word":"Hallo"}$json$::jsonb, 0),
('dictation-Danke', 'dictation-word', $json${"word":"Danke"}$json$::jsonb, 1),
('dictation-Bitte', 'dictation-word', $json${"word":"Bitte"}$json$::jsonb, 2),
('dictation-Haus', 'dictation-word', $json${"word":"Haus"}$json$::jsonb, 3),
('dictation-Buch', 'dictation-word', $json${"word":"Buch"}$json$::jsonb, 4),
('dictation-Zug', 'dictation-word', $json${"word":"Zug"}$json$::jsonb, 5),
('dictation-Name', 'dictation-word', $json${"word":"Name"}$json$::jsonb, 6),
('dictation-Wasser', 'dictation-word', $json${"word":"Wasser"}$json$::jsonb, 7),
('dictation-Schule', 'dictation-word', $json${"word":"Schule"}$json$::jsonb, 8),
('dictation-Freund', 'dictation-word', $json${"word":"Freund"}$json$::jsonb, 9),
('dictation-Morgen', 'dictation-word', $json${"word":"Morgen"}$json$::jsonb, 10),
('dictation-Mutter', 'dictation-word', $json${"word":"Mutter"}$json$::jsonb, 11)
ON CONFLICT (content_type, id) DO UPDATE SET payload = EXCLUDED.payload, sort = EXCLUDED.sort;

-- story-sentence (8 rows)
INSERT INTO public.content_items (id, content_type, payload, sort) VALUES
('story-1-s1-1', 'story-sentence', $json${"storyId":"story-1","title":"Morgenroutine","titleNe":"बिहानको दिनचर्या","titleEn":"Morning Routine","level":"A1","sentence":{"id":"s1-1","de":"Guten Morgen!","ne":"शुभ प्रभात!","en":"Good morning!","words":[{"de":"Guten","ne":"शुभ","en":"Good"},{"de":"Morgen","ne":"बिहान","en":"morning"}]}}$json$::jsonb, 0),
('story-1-s1-2', 'story-sentence', $json${"storyId":"story-1","title":"Morgenroutine","titleNe":"बिहानको दिनचर्या","titleEn":"Morning Routine","level":"A1","sentence":{"id":"s1-2","de":"Heute ist Montag.","ne":"आज सोमबार हो।","en":"Today is Monday.","words":[{"de":"Heute","ne":"आज","en":"Today"},{"de":"ist","ne":"हो","en":"is"},{"de":"Montag","ne":"सोमबार","en":"Monday"}]}}$json$::jsonb, 1),
('story-1-s1-3', 'story-sentence', $json${"storyId":"story-1","title":"Morgenroutine","titleNe":"बिहानको दिनचर्या","titleEn":"Morning Routine","level":"A1","sentence":{"id":"s1-3","de":"Es ist das Jahr 2026.","ne":"यो २०२६ साल हो।","en":"It is the year 2026.","words":[{"de":"Es","ne":"यो","en":"It"},{"de":"ist","ne":"हो","en":"is"},{"de":"das","ne":"","en":"the"},{"de":"Jahr","ne":"वर्ष","en":"year"}]}}$json$::jsonb, 2),
('story-2-s2-1', 'story-sentence', $json${"storyId":"story-2","title":"Im Café","titleNe":"क्याफेमा","titleEn":"At the Café","level":"A1","sentence":{"id":"s2-1","de":"Hallo! Wie geht es dir?","ne":"नमस्ते! तिमीलाई कस्तो छ?","en":"Hello! How are you?","words":[{"de":"Hallo","ne":"नमस्ते","en":"Hello"},{"de":"Wie","ne":"कसरी","en":"How"},{"de":"geht","ne":"जान्छ","en":"goes"},{"de":"es","ne":"यो","en":"it"},{"de":"dir","ne":"तिमीलाई","en":"you"}]}}$json$::jsonb, 0),
('story-2-s2-2', 'story-sentence', $json${"storyId":"story-2","title":"Im Café","titleNe":"क्याफेमा","titleEn":"At the Café","level":"A1","sentence":{"id":"s2-2","de":"Danke, gut!","ne":"धन्यवाद, राम्रो!","en":"Thank you, good!","words":[{"de":"Danke","ne":"धन्यवाद","en":"Thank you"},{"de":"gut","ne":"राम्रो","en":"good"}]}}$json$::jsonb, 1),
('story-2-s2-3', 'story-sentence', $json${"storyId":"story-2","title":"Im Café","titleNe":"क्याफेमा","titleEn":"At the Café","level":"A1","sentence":{"id":"s2-3","de":"Auf Wiedersehen!","ne":"फेरी भेटौंला!","en":"Goodbye!","words":[{"de":"Auf","ne":"","en":"On/Until"},{"de":"Wiedersehen","ne":"फेरी भेट्ने","en":"seeing again"}]}}$json$::jsonb, 2),
('story-3-s3-1', 'story-sentence', $json${"storyId":"story-3","title":"Die Woche","titleNe":"हप्ता","titleEn":"The Week","level":"A1","sentence":{"id":"s3-1","de":"Montag, Dienstag, Mittwoch.","ne":"सोमबार, मंगलबार, बुधबार।","en":"Monday, Tuesday, Wednesday.","words":[{"de":"Montag","ne":"सोमबार","en":"Monday"},{"de":"Dienstag","ne":"मंगलबार","en":"Tuesday"},{"de":"Mittwoch","ne":"बुधबार","en":"Wednesday"}]}}$json$::jsonb, 0),
('story-3-s3-2', 'story-sentence', $json${"storyId":"story-3","title":"Die Woche","titleNe":"हप्ता","titleEn":"The Week","level":"A1","sentence":{"id":"s3-2","de":"Ich lerne jeden Tag Deutsch.","ne":"म हरेक दिन जर्मन सिक्छु।","en":"I learn German every day.","words":[{"de":"Ich","ne":"म","en":"I"},{"de":"lerne","ne":"सिक्छु","en":"learn"},{"de":"jeden","ne":"हरेक","en":"every"},{"de":"Tag","ne":"दिन","en":"day"},{"de":"Deutsch","ne":"जर्मन","en":"German"}]}}$json$::jsonb, 1)
ON CONFLICT (content_type, id) DO UPDATE SET payload = EXCLUDED.payload, sort = EXCLUDED.sort;

-- rapidfire-question (24 rows)
INSERT INTO public.content_items (id, content_type, payload, sort) VALUES
('rapid-vocab-trans-1', 'rapidfire-question', $json${"id":"vocab-trans-1","type":"vocabulary-translation","timeLimit":5000,"english":"apple","german":"apfel","options":["apfel","haus","Auto"]}$json$::jsonb, 0),
('rapid-vocab-trans-2', 'rapidfire-question', $json${"id":"vocab-trans-2","type":"vocabulary-translation","timeLimit":5000,"english":"water","german":"wasser","options":["Wasser","Brot","Hund"]}$json$::jsonb, 1),
('rapid-vocab-trans-3', 'rapidfire-question', $json${"id":"vocab-trans-3","type":"vocabulary-translation","timeLimit":5000,"english":"friend","german":"Freund","options":["Freundin","Freund","Frei"]}$json$::jsonb, 2),
('rapid-vocab-trans-4', 'rapidfire-question', $json${"id":"vocab-trans-4","type":"vocabulary-translation","timeLimit":5000,"english":"book","german":"Buch","options":["Buch","Baum","Bank"]}$json$::jsonb, 3),
('rapid-audio-comp-1', 'rapidfire-question', $json${"id":"audio-comp-1","type":"audio-comprehension","timeLimit":6000,"word":"Haus","meaning":"house","options":["house","home","yard"]}$json$::jsonb, 0),
('rapid-audio-comp-2', 'rapidfire-question', $json${"id":"audio-comp-2","type":"audio-comprehension","timeLimit":6000,"word":"Buch","meaning":"book","options":["book","table","chair"]}$json$::jsonb, 1),
('rapid-audio-comp-3', 'rapidfire-question', $json${"id":"audio-comp-3","type":"audio-comprehension","timeLimit":6000,"word":"Freund","meaning":"friend","options":["friend","teacher","doctor"]}$json$::jsonb, 2),
('rapid-audio-comp-4', 'rapidfire-question', $json${"id":"audio-comp-4","type":"audio-comprehension","timeLimit":6000,"word":"Wasser","meaning":"water","options":["water","milk","juice"]}$json$::jsonb, 3),
('rapid-article-1', 'rapidfire-question', $json${"id":"article-1","type":"article-precision","timeLimit":4000,"noun":"Apfel","article":"der"}$json$::jsonb, 0),
('rapid-article-2', 'rapidfire-question', $json${"id":"article-2","type":"article-precision","timeLimit":4000,"noun":"Tisch","article":"der"}$json$::jsonb, 1),
('rapid-article-3', 'rapidfire-question', $json${"id":"article-3","type":"article-precision","timeLimit":4000,"noun":"Tür","article":"die"}$json$::jsonb, 2),
('rapid-article-4', 'rapidfire-question', $json${"id":"article-4","type":"article-precision","timeLimit":4000,"noun":"Haus","article":"das"}$json$::jsonb, 3),
('rapid-number-1', 'rapidfire-question', $json${"id":"number-1","type":"number-conversion","timeLimit":5000,"number":5,"germanText":"fünf","direction":"digit-to-text","options":["fünf","zehn","eins"]}$json$::jsonb, 0),
('rapid-number-2', 'rapidfire-question', $json${"id":"number-2","type":"number-conversion","timeLimit":5000,"number":12,"germanText":"zwölf","direction":"text-to-digit","options":["12","21","2"]}$json$::jsonb, 1),
('rapid-number-3', 'rapidfire-question', $json${"id":"number-3","type":"number-conversion","timeLimit":5000,"number":20,"germanText":"zwanzig","direction":"digit-to-text","options":["zwanzig","fünfzehn","dreißig"]}$json$::jsonb, 2),
('rapid-number-4', 'rapidfire-question', $json${"id":"number-4","type":"number-conversion","timeLimit":5000,"number":30,"germanText":"dreißig","direction":"text-to-digit","options":["30","31","20"]}$json$::jsonb, 3),
('rapid-verb-1', 'rapidfire-question', $json${"id":"verb-1","type":"verb-conjugation","timeLimit":5000,"pronoun":"ich","verb":"sein","conjugated":"bin","options":["bin","bist","ist"]}$json$::jsonb, 0),
('rapid-verb-2', 'rapidfire-question', $json${"id":"verb-2","type":"verb-conjugation","timeLimit":5000,"pronoun":"du","verb":"haben","conjugated":"hast","options":["habe","hast","hat"]}$json$::jsonb, 1),
('rapid-verb-3', 'rapidfire-question', $json${"id":"verb-3","type":"verb-conjugation","timeLimit":5000,"pronoun":"er","verb":"machen","conjugated":"macht","options":["mache","macht","machen"]}$json$::jsonb, 2),
('rapid-verb-4', 'rapidfire-question', $json${"id":"verb-4","type":"verb-conjugation","timeLimit":5000,"pronoun":"wir","verb":"gehen","conjugated":"gehen","options":["gehe","gehen","geht"]}$json$::jsonb, 3),
('rapid-pron-1', 'rapidfire-question', $json${"id":"pron-1","type":"pronunciation-reading","timeLimit":7000,"text":"Haus","meaning":"house","audio":"Haus","options":["Haus","Hase","Haut"]}$json$::jsonb, 0),
('rapid-pron-2', 'rapidfire-question', $json${"id":"pron-2","type":"pronunciation-reading","timeLimit":7000,"text":"Buch","meaning":"book","audio":"Buch","options":["Buch","Baden","Burg"]}$json$::jsonb, 1),
('rapid-pron-3', 'rapidfire-question', $json${"id":"pron-3","type":"pronunciation-reading","timeLimit":7000,"text":"Freund","meaning":"friend","audio":"Freund","options":["Freund","Früh","Frei"]}$json$::jsonb, 2),
('rapid-pron-4', 'rapidfire-question', $json${"id":"pron-4","type":"pronunciation-reading","timeLimit":7000,"text":"Wasser","meaning":"water","audio":"Wasser","options":["Wasser","Wald","Werk"]}$json$::jsonb, 3)
ON CONFLICT (content_type, id) DO UPDATE SET payload = EXCLUDED.payload, sort = EXCLUDED.sort;

-- spelling-word (18 rows)
INSERT INTO public.content_items (id, content_type, payload, sort) VALUES
('spelling-easy-JA', 'spelling-word', $json${"word":"JA","meaning":"Yes / हो","letters":["J","A"],"difficulty":"easy"}$json$::jsonb, 0),
('spelling-easy-HAUS', 'spelling-word', $json${"word":"HAUS","meaning":"House / घर","letters":["H","A","U","S"],"difficulty":"easy"}$json$::jsonb, 1),
('spelling-easy-GUT', 'spelling-word', $json${"word":"GUT","meaning":"Good / राम्रो","letters":["G","U","T"],"difficulty":"easy"}$json$::jsonb, 2),
('spelling-easy-TEE', 'spelling-word', $json${"word":"TEE","meaning":"Tea / चिया","letters":["T","E","E"],"difficulty":"easy"}$json$::jsonb, 3),
('spelling-easy-UHR', 'spelling-word', $json${"word":"UHR","meaning":"Clock / घडी","letters":["U","H","R"],"difficulty":"easy"}$json$::jsonb, 4),
('spelling-easy-NAME', 'spelling-word', $json${"word":"NAME","meaning":"Name / नाम","letters":["N","A","M","E"],"difficulty":"easy"}$json$::jsonb, 5),
('spelling-easy-BUCH', 'spelling-word', $json${"word":"BUCH","meaning":"Book / किताब","letters":["B","U","C","H"],"difficulty":"easy"}$json$::jsonb, 6),
('spelling-easy-ZUG', 'spelling-word', $json${"word":"ZUG","meaning":"Train / रेल","letters":["Z","U","G"],"difficulty":"easy"}$json$::jsonb, 7),
('spelling-easy-AUTO', 'spelling-word', $json${"word":"AUTO","meaning":"Car / गाडी","letters":["A","U","T","O"],"difficulty":"easy"}$json$::jsonb, 8),
('spelling-easy-KIND', 'spelling-word', $json${"word":"KIND","meaning":"Child / बच्चा","letters":["K","I","N","D"],"difficulty":"easy"}$json$::jsonb, 9),
('spelling-medium-WASSER', 'spelling-word', $json${"word":"WASSER","meaning":"Water / पानी","letters":["W","A","S","S","E","R"],"difficulty":"medium"}$json$::jsonb, 0),
('spelling-medium-VATER', 'spelling-word', $json${"word":"VATER","meaning":"Father / बुबा","letters":["V","A","T","E","R"],"difficulty":"medium"}$json$::jsonb, 1),
('spelling-medium-MUTTER', 'spelling-word', $json${"word":"MUTTER","meaning":"Mother / आमा","letters":["M","U","T","T","E","R"],"difficulty":"medium"}$json$::jsonb, 2),
('spelling-medium-SCHULE', 'spelling-word', $json${"word":"SCHULE","meaning":"School / स्कूल","letters":["S","C","H","U","L","E"],"difficulty":"medium"}$json$::jsonb, 3),
('spelling-medium-FREUND', 'spelling-word', $json${"word":"FREUND","meaning":"Friend / साथी","letters":["F","R","E","U","N","D"],"difficulty":"medium"}$json$::jsonb, 4),
('spelling-medium-MORGEN', 'spelling-word', $json${"word":"MORGEN","meaning":"Morning / बिहान","letters":["M","O","R","G","E","N"],"difficulty":"medium"}$json$::jsonb, 5),
('spelling-medium-NACHT', 'spelling-word', $json${"word":"NACHT","meaning":"Night / रात","letters":["N","A","C","H","T"],"difficulty":"medium"}$json$::jsonb, 6),
('spelling-medium-ARBEIT', 'spelling-word', $json${"word":"ARBEIT","meaning":"Work / काम","letters":["A","R","B","E","I","T"],"difficulty":"medium"}$json$::jsonb, 7)
ON CONFLICT (content_type, id) DO UPDATE SET payload = EXCLUDED.payload, sort = EXCLUDED.sort;

-- pronunciation-tip (12 rows)
INSERT INTO public.content_items (id, content_type, payload, sort) VALUES
('pron-tip-Ae', 'pronunciation-tip', $json${"letterId":"Ae","en":"Like the \"e\" in \"bed\", but with lips spread wide. Say \"eh\" with a smile.","ne":"अंग्रेजीको \"bed\" को \"e\" जस्तै, तर ओठ फराकिलो पारेर। \"ए\" भन्नुहोस्।"}$json$::jsonb, 0),
('pron-tip-Oe', 'pronunciation-tip', $json${"letterId":"Oe","en":"Round your lips like \"o\", then say \"e\". Like the French \"eu\".","ne":"ओठलाई \"ओ\" जस्तै गोलो पारेर \"ए\" भन्नुहोस्। फ्रेन्च \"eu\" जस्तै।"}$json$::jsonb, 0),
('pron-tip-Ue', 'pronunciation-tip', $json${"letterId":"Ue","en":"Round your lips like \"u\", then say \"ee\". Like the French \"u\".","ne":"ओठलाई \"उ\" जस्तै गोलो पारेर \"ई\" भन्नुहोस्। फ्रेन्च \"u\" जस्तै।"}$json$::jsonb, 0),
('pron-tip-Sz', 'pronunciation-tip', $json${"letterId":"Sz","en":"A sharp \"s\" sound, like \"ss\" in \"hiss\". Never a \"z\" sound.","ne":"तीखो \"स\" ध्वनि, अंग्रेजीको \"hiss\" को \"ss\" जस्तै। कहिल्यै \"ज\" जस्तो होइन।"}$json$::jsonb, 0),
('pron-tip-R', 'pronunciation-tip', $json${"letterId":"R","en":"A soft rolled \"r\" at the back of the throat, or a light tap like Spanish \"r\".","ne":"घाँटीको पछाडिबाट हल्का गड्गडाउने \"र\", वा स्पेनिस \"r\" जस्तै हल्का ट्याप।"}$json$::jsonb, 0),
('pron-tip-Z', 'pronunciation-tip', $json${"letterId":"Z","en":"Say \"ts\" together, like \"ts\" in \"cats\". Not a \"z\" sound.","ne":"\"ts\" सँगै भन्नुहोस्, अंग्रेजीको \"cats\" को \"ts\" जस्तै। \"ज\" ध्वनि होइन।"}$json$::jsonb, 0),
('pron-tip-C', 'pronunciation-tip', $json${"letterId":"C","en":"Before e/i: \"ts\". Otherwise like \"k\".","ne":"\"e\" वा \"i\" अघि: \"ts\"। अन्यथा \"k\" जस्तै।"}$json$::jsonb, 0),
('pron-tip-V', 'pronunciation-tip', $json${"letterId":"V","en":"Usually pronounced like \"f\" in German words.","ne":"जर्मन शब्दहरूमा प्रायः \"f\" जस्तै उच्चारण हुन्छ।"}$json$::jsonb, 0),
('pron-tip-W', 'pronunciation-tip', $json${"letterId":"W","en":"Like English \"v\" — lips touch the teeth.","ne":"अंग्रेजीको \"v\" जस्तै — ओठ दाँतमा छुन्छन्।"}$json$::jsonb, 0),
('pron-tip-J', 'pronunciation-tip', $json${"letterId":"J","en":"Like English \"y\" in \"yes\".","ne":"अंग्रेजीको \"yes\" को \"y\" जस्तै।"}$json$::jsonb, 0),
('pron-tip-S', 'pronunciation-tip', $json${"letterId":"S","en":"Before a vowel: like \"z\". Otherwise: like \"s\".","ne":"स्वर अघि: \"z\" जस्तै। अन्यथा: \"s\" जस्तै।"}$json$::jsonb, 0),
('pron-tip-H', 'pronunciation-tip', $json${"letterId":"H","en":"A breathy \"h\", like English \"h\" in \"hat\".","ne":"सास फेर्ने \"h\", अंग्रेजीको \"hat\" को \"h\" जस्तै।"}$json$::jsonb, 0)
ON CONFLICT (content_type, id) DO UPDATE SET payload = EXCLUDED.payload, sort = EXCLUDED.sort;
